name: Run Tests

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: composer install
    - name: Run lint
      run: vendor/bin/phpcs 
    - name: Run test
      run: php artisan test
